controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Rutas de Biblioteca
index:
    path: /
    methods: [GET]
    controller: App\Controller\LibraryController::index

showLibraryById:
    path: /library/{id}
    methods: [GET]
    controller: App\Controller\LibraryController::showLibraryById
    requirements:
        id: \d+

#showLibraryByName:
    #path: /library/
    #controller: App\Controller\LibraryController::showLibraryByName

indexAdminLibraries:
    path: /admin/library/
    methods: [GET]
    controller: App\Controller\LibraryController::indexAdminLibraries

newLibrary:
    path: /admin/library/new
    methods: [GET, POST]
    controller: App\Controller\LibraryController::newLibrary

showAdminLibraryById:
    path: /admin/library/{id}
    methods: [GET]
    controller: App\Controller\LibraryController::showAdminLibraryById
    requirements:
        id: \d+

editLibrary:
    path: /admin/library/{id}/edit
    methods: [GET, POST]
    controller: App\Controller\LibraryController::editLibrary

deleteLibrary:
    path: /admin/library/{id}
    methods: [POST]
    controller: App\Controller\LibraryController::deleteLibrary





